### ISSUE TITLE
Add xscope_fclose()

### ISSUE THREAD

**Issue by shuchitak** [xmos/xscope_fileio#11]
An xscope_fclose() function would be nice to have so that individual files can be closed. Having this would make it easier to switch between xscope_fileio and x86 compile through a #define. At the moment, xscope_close_all_files() needs to be called from the test code only when xscope_fileio is enabled.

**Comment by xalbertoisorna** [comment]
> An xscope_fclose() function would be nice to have so that individual files can be closed. Having this would make it easier to switch between xscope_fileio and x86 compile through a #define. At the moment, xscope_close_all_files() needs to be called from the test code only when xscope_fileio is enabled.

Closed by #66
