### ISSUE TITLE
Version 0.4.0 does not keep up and causes avona tests to fail

### ISSUE THREAD

**Issue by ed-xmos** [xmos/xscope_fileio#19]
We have reverted to 0.3.2 for avona tests because the 0.4.0 "fixes" which redirect STDIO to the console and return as a string does not keep up in some cases.

Unfortunately 0.3.2 can only either print to the console OR redirect to a file, so this should be fixed ideally.

The best fix would be to add fileio to xscope in the tools, which would make this module obsolete (note to @MarkPhillips-xmos)

**Comment by mbanth** [comment]
Closing as out-of-date since the current release is v1.1.2.
