### ISSUE TITLE
xscope_fileio cannot be used with FreeRTOS

### ISSUE THREAD

**Issue by xmos-jmccarthy** [xmos/xscope_fileio#27]
The current xscope_fileio requires a hardware lock for mutual exclusion during file operations.  Current XS3A chips have 4 hardware locks per tile.  The std libs consume 1.  The xscope service consumes 1.  FreeRTOS consumes 2.

In the FreeRTOS use case, RTOS based mutexes can be used to achieve the same functionality.

**Comment by mbanth** [comment]
@xmos-jmccarthy, please add Story Points to this issue estimating the amount of effort required by it.  We're using 1 SP = 1 engineer-day of effort.  Thanks.
